# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMBMdT663wzWvgvAvU4jFVXRaSI4yPdA
"""

from fastapi import FastAPI, HTTPException
import os
import joblib
import pandas as pd
import json
from datetime import datetime
import requests

# --------------------------------------------------
# Backend configuration
# --------------------------------------------------
BACKEND_BASE_URL = "https://ml-waf-vgb9.onrender.com"
ANOMALY_ENDPOINT = f"{BACKEND_BASE_URL}/api/anomalies"

def send_anomaly_to_backend(client_ip, uri, ml_decision, confidence):
    payload = {
        "client_ip": client_ip,
        "uri": uri,
        "mlDecision": ml_decision,
        "confidence": round(float(confidence), 3)
    }

    try:
        response = requests.post(
            ANOMALY_ENDPOINT,
            json=payload,
            timeout=5  # slightly higher for cloud
        )
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        # Never block traffic because backend is slow/down
        print("Failed to send anomaly to Render backend:", str(e))


# --------------------------------------------------
# FastAPI app
# --------------------------------------------------
app = FastAPI(title="WAF ML Inference Service")

# --------------------------------------------------
# Load ML model (ABSOLUTE PATH - WINDOWS SAFE)
# --------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

MODEL_PATH = os.path.join(
    BASE_DIR,
    "..",
    "model",
    "waf_log_trained_model.pkl"
)

print("Loading model from:", MODEL_PATH)
model = joblib.load(MODEL_PATH)

# --------------------------------------------------
# Feature columns (MUST MATCH TRAINING)
# --------------------------------------------------
FEATURE_COLUMNS = [
    "status_code",
    "anomaly_score",
    "host_is_ip",
    "scanner_ua",
    "uri_length",
    "user_agent_length",
    "waf_warning"
]

# --------------------------------------------------
# Inference endpoint
# --------------------------------------------------
@app.post("/infer")
def infer(payload: dict):
    try:
        # 1. Extract features
        features = payload["features"]

        # 2. Prepare model input
        df = pd.DataFrame([features])[FEATURE_COLUMNS]

        # 3. Predict
        pred = model.predict(df)[0]
        prob = model.predict_proba(df)[0][1]

        decision = "BLOCK" if pred == 1 else "ALLOW"
        ml_decision = "BAD" if decision == "BLOCK" else "GOOD"

        # 4. Send anomaly to backend ONLY if BAD
        if ml_decision == "BAD":
            send_anomaly_to_backend(
                client_ip=payload.get("client_ip"),
                uri=payload.get("uri"),
                ml_decision=ml_decision,
                confidence=prob
            )

        # 5. Log locally for dashboard (NDJSON)
        log_record = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "client_ip": payload.get("client_ip"),
            "method": payload.get("method"),
            "uri": payload.get("uri"),
            "status_code": features.get("status_code"),
            "features": features,
            "ml": {
                "decision": ml_decision,
                "confidence": round(float(prob), 3),
                "model": "WAF_Model_v1"
            },
            "finalDecision": "PENDING",
            "reviewedByAdmin": False
        }

        LOG_PATH = os.path.join(
            BASE_DIR,
            "..",
            "logs",
            "ml_decisions.json"
        )

        with open(LOG_PATH, "a") as f:
            f.write(json.dumps(log_record) + "\n")

        # 6. Return response
        return {
            "decision": decision,
            "attack_probability": round(float(prob), 3)
        }

    except KeyError as e:
        raise HTTPException(
            status_code=400,
            detail=f"Missing field: {str(e)}"
        )

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )